# Generated by Django 4.0 on 2021-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='stat',
            field=models.IntegerField(default=0),
        ),
    ]
