# Generated by Django 4.0 on 2022-01-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='payment_period',
            field=models.IntegerField(null=True),
        ),
    ]
